import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Language = 'en' | 'sw';

// Translation keys
export const translations = {
  en: {
    // Common
    app_name: 'SunHarvest Connect',
    loading: 'Loading...',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    filter: 'Filter',
    all: 'All',
    view_all: 'View All',
    back: 'Back',
    continue: 'Continue',
    submit: 'Submit',
    close: 'Close',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    error: 'Error',
    success: 'Success',
    retry: 'Retry',

    // Auth
    welcome: 'Welcome',
    login: 'Login',
    register: 'Register',
    phone_number: 'Phone Number',
    enter_phone: 'Enter your phone number',
    pin: 'PIN',
    enter_pin: 'Enter your 4-digit PIN',
    create_pin: 'Create a 4-digit PIN',
    confirm_pin: 'Confirm PIN',
    name: 'Full Name',
    enter_name: 'Enter your full name',
    location: 'Location',
    select_county: 'Select your county',
    user_type: 'I am a...',
    farmer: 'Farmer',
    buyer: 'Buyer',
    transporter: 'Transporter',
    login_success: 'Login successful',
    register_success: 'Registration successful',
    invalid_credentials: 'Invalid phone or PIN',
    app_subtitle: 'AI-powered marketplace for Kenyan farmers. Get fair prices for your produce.',
    ai_quality_grading: 'AI quality grading',
    real_time_market_prices: 'Real-time market prices',
    direct_buyer_connections: 'Direct buyer connections',
    get_started: 'Get Started',
    have_account: 'Already have an account?',
    quick_demo: 'Quick Demo',
    try_demo: 'Try the app instantly as:',
    sign_in_subtitle: 'Sign in to access your account',
    register_subtitle: 'Join thousands of farmers getting fair prices',
    missing_fields: 'Missing Fields',
    missing_fields_login: 'Please enter phone and PIN',
    missing_fields_register: 'Please fill all fields',
    invalid_pin: 'Invalid PIN',
    invalid_pin_message: 'PIN must be 4 digits',
    pin_mismatch: 'PIN Mismatch',
    pin_mismatch_message: 'PINs do not match',
    login_failed: 'Login Failed',
    login_failed_default: 'Login failed. Please check your credentials.',
    registration_failed: 'Registration Failed',
    registration_failed_default: 'Registration failed. Please try again.',
    demo_login_failed: 'Demo Login Failed',
    demo_login_failed_message: 'Make sure the backend is running and database is seeded.\n\nRun: npx ts-node scripts/seedListings.ts',
    no_account: "Don't have an account?",
    consent_agree: 'I agree to the',
    consent_privacy_policy: 'Privacy Policy',
    consent_and: 'and',
    consent_terms: 'Terms of Service',
    consent_dpa: 'as required by the Kenya Data Protection Act 2019.',
    consent_required: 'Consent Required',
    consent_required_message: 'You must agree to the Privacy Policy and Terms of Service to create an account.',
    demo_login_as: 'Demo login as %1',

    // Navigation
    home: 'Home',
    dashboard: 'Dashboard',
    sell: 'Sell',
    market: 'Market',
    orders: 'Orders',
    jobs: 'Jobs',
    deliveries: 'Deliveries',
    profile: 'Profile',
    sacco: 'SACCO',

    // Dashboard
    good_morning: 'Good morning',
    good_afternoon: 'Good afternoon',
    good_evening: 'Good evening',
    ai_insights: 'AI Insights',
    quick_actions: 'Quick Actions',
    market_prices: 'Market Prices',
    view_trends: 'View trends',
    todays_weather: "Today's Weather",
    create_listing: 'Create Listing',
    browse_market: 'Browse Market',
    grade_and_list: 'Grade & list your produce',
    find_fresh_produce: 'Find fresh produce near you',
    find_deliveries: 'Find delivery jobs near you',
    ai_prices: 'AI Prices',
    my_orders: 'My Orders',
    total_revenue: 'Total Revenue',
    total_spent: 'Total Spent',
    total_earnings: 'Total Earnings',
    listings: 'Listings',
    offers: 'Offers',
    rating: 'Rating',
    views: 'views',
    sales: 'sales',
    this_month: 'this month',
    sold: 'sold',
    total: 'total',
    reviews: 'reviews',
    purchases: 'purchases',
    active_now: 'active now',
    ai_grade: 'AI Grade',

    // Market
    marketplace: 'Marketplace',
    market_intelligence: 'Market Intelligence',
    available_listings: 'Available Listings',
    todays_market_prices: "Today's Market Prices",
    live: 'Live',
    search_crops: 'Search crops, farmers, locations...',
    no_listings: 'No Listings Found',
    check_back: 'Check back later for new listings',
    per_kg: 'per kg',
    kg_available: 'kg available',
    make_offer: 'Make Offer',
    ai_graded: 'AI Graded',
    contact_farmer: 'Contact Farmer',
    contact_buyer: 'Contact Buyer',
    call: 'Call',
    whatsapp: 'WhatsApp',
    escrow_protection: 'Escrow Protection',
    escrow_description: 'Your payment is held securely until you confirm delivery',

    // Sell/Create Listing
    sell_produce: 'Sell Produce',
    what_selling: 'What are you selling?',
    select_crop: 'Select crop type and enter details',
    crop_type: 'Crop Type',
    quantity: 'Quantity',
    quantity_kg: 'Quantity (kg)',
    price: 'Price',
    price_per_kg: 'Price per kg (KSh)',
    description: 'Description',
    description_optional: 'Description (optional)',
    add_photos: 'Add Photos',
    upload_photos: 'Upload at least 2 photos for AI quality grading',
    camera: 'Camera',
    gallery: 'Gallery',
    run_ai_grading: 'Run AI Quality Grading',
    ai_quality_grade: 'AI Quality Grade',
    confident: 'confident',
    suggested_price: 'Suggested Price',
    harvest_details: 'Harvest Details',
    harvest_date: 'Harvest Date',
    available_for: 'Available for (days)',
    storage_conditions: 'Storage Conditions',
    cool_dry: 'Cool & Dry',
    refrigerated: 'Refrigerated',
    room_temp: 'Room Temp',
    delivery_options: 'Delivery Options',
    pickup_and_review: 'Pickup & Review',
    set_pickup_location: 'Set where buyers or transporters can collect your produce',
    delivery_by_transporters: 'Delivery handled by transporters',
    transporter_info: 'Verified transporters on SunHarvest will deliver to buyers. You just prepare for pickup.',
    use_price: 'Use this price',
    your_price: 'Your current price',
    pickup_location: 'Pickup Location',
    delivery_available: 'Delivery Available?',
    delivery_radius: 'Delivery Radius (km)',
    listing_summary: 'Listing Summary',
    total_value: 'Total Value',
    publish_listing: 'Publish Listing',
    listing_published: 'Listing Published!',
    listing_failed: 'Failed to publish listing. Please try again.',
    listing_live: 'Your listing is now live on the marketplace.',

    // Orders
    active: 'Active',
    history: 'History',
    pending: 'Pending',
    accepted: 'Accepted',
    paid: 'Paid',
    in_transit: 'In Transit',
    delivered: 'Delivered',
    completed: 'Completed',
    cancelled: 'Cancelled',
    disputed: 'Disputed',
    no_orders: 'No orders',
    accept_offer: 'Accept Offer',
    decline_offer: 'Decline Offer',
    offer_accepted: 'Offer accepted',
    offer_declined: 'Offer declined',
    pay_mpesa: 'Pay with M-Pesa',
    payment_initiated: 'Payment Initiated',
    check_phone: 'Check your phone for M-Pesa prompt.',
    confirm_delivery: 'Confirm Delivery',
    confirm_receipt: 'Confirm Receipt',
    delivery_confirmed: 'Delivery Confirmed',
    payment_released: 'Payment has been released to the farmer.',
    mark_delivered: 'Mark as Delivered',
    escrow_held: 'Funds held in escrow',
    total_amount: 'Total Amount',
    order_details: 'Order Details',

    // Trust Score
    trust_score: 'Trust Score',
    your_trust_score: 'Your Trust Score',
    transactions: 'Transactions',
    member_since: 'Member Since',
    achievements: 'Achievements',
    score_breakdown: 'Score Breakdown',
    completion_rate: 'Completion Rate',
    partner_rating: 'Partner Rating',
    account_age: 'Account Age',
    verification: 'Verification',
    response_time: 'Response Time',
    dispute_history: 'Dispute History',
    ai_insights_title: 'AI Insights',

    // Profile
    account_info: 'Account Information',
    account_information: 'Account Information',
    transaction_history: 'Transaction History',
    select_language: 'Select Language',
    tagline: 'Empowering Kenyan Farmers',
    recent_activity: 'Recent Activity',
    settings: 'Settings',
    push_notifications: 'Push Notifications',
    sms_alerts: 'SMS Alerts',
    edit_profile: 'Edit Profile',
    change_pin: 'Change PIN',
    language: 'Language',
    english: 'English',
    swahili: 'Kiswahili',
    support: 'Support',
    help_center: 'Help Center',
    contact_support: 'Contact Support',
    terms_privacy: 'Terms & Privacy',
    privacy_policy: 'Privacy Policy',
    delete_account: 'Delete Account',
    about: 'About SunHarvest',
    logout: 'Log Out',
    logout_confirm: 'Are you sure you want to log out?',
    verify_account: 'Verify Account',
    verified: 'Verified',

    // Deliveries (Transporter)
    available_jobs: 'Available Jobs',
    my_jobs: 'My Jobs',
    todays_earnings: "Today's Earnings",
    active_jobs: 'Active Jobs',
    pickup: 'Pickup',
    delivery: 'Delivery',
    distance: 'Distance',
    payment: 'Payment',
    deadline: 'Deadline',
    accept_job: 'Accept Job',
    job_accepted: 'Job accepted!',
    contact_farmer_pickup: 'Contact the farmer to arrange pickup.',
    cargo_info: 'Cargo Information',
    route: 'Route',
    contacts: 'Contacts',
    special_instructions: 'Special Instructions',
    mark_picked_up: 'Mark as Picked Up',
    start_delivery: 'Start Delivery',
    complete_get_paid: 'Complete & Get Paid',
    ai_route_suggestion: 'AI Route Suggestion',

    // AI Features
    ai_price_suggestion: 'AI Price Suggestion',
    recommended_price: 'Recommended Price',
    market_average: 'Market Average',
    price_trend: 'Price Trend',
    rising: 'Rising',
    stable: 'Stable',
    falling: 'Falling',
    demand_level: 'Demand Level',
    high: 'High',
    normal: 'Normal',
    low: 'Low',
    success_estimate: 'Success Estimate',
    estimated_days: 'Estimated Days to Sell',
    probability: 'Sale Probability',
    fast: 'Fast',
    slow: 'Slow',
    unlikely: 'Unlikely',

    // Grades
    premium: 'Premium',
    grade_a: 'Grade A',
    grade_b: 'Grade B',
    grade_c: 'Grade C',
    reject: 'Reject',
    grade: 'Grade',
    grade_produce: 'Grade Produce',
    take_photo: 'Take a photo of your produce',
    instant_grading_subtitle: 'Get instant quality grading and price suggestion',
    open_camera: 'Open Camera',
    choose_gallery: 'Choose from Gallery',
    what_grading: 'What are you grading?',
    select_from_gallery: 'Select from Gallery',
    analyzing: 'Analyzing...',
    analyze_quality: 'Analyze Quality',
    quality_analysis: 'Quality Analysis',
    quality_grade: 'Quality Grade',
    confidence: 'Confidence',
    grade_details: 'Grade Details',
    freshness: 'Freshness',
    size_uniformity: 'Size Uniformity',
    color_quality: 'Color Quality',
    defects: 'Defects',
    recommendations: 'Recommendations',
    price_range: 'Price Range',
    market_trend: 'Market Trend',
    notes: 'Notes',
    list_for_sale: 'List for Sale',
    grade_another: 'Grade Another',
    retake_photo: 'Retake Photo',
    list_your_produce: 'List Your Produce',
    your_price_optional: 'Your Price (optional)',
    creating: 'Creating...',
    select_crop_type: 'Select Crop Type',
    listing_created: 'Listing Created!',
    permission_needed: 'Permission needed',
    missing_info: 'Missing Info',
    camera_roll_required: 'Camera roll access is required',
    camera_required: 'Camera access is required',

    // SACCO
    total_savings: 'Total Savings',
    interest_earned: 'Interest Earned',
    loan_balance: 'Loan Balance',
    credit_score: 'Credit Score',
    make_contribution: 'Make Contribution',
    apply_loan: 'Apply for Loan',
    loan_products: 'Loan Products',
    recent_transactions: 'Recent Transactions',
    my_sacco_groups: 'My SACCO Groups',
    join_sacco: 'Join a SACCO',
    active_loans: 'Active Loans',
    make_repayment: 'Make Repayment',
    loan_terms: 'Loan Terms',
    pay_mpesa_prompt: 'Check your phone for M-Pesa prompt',
    contribution_amount: 'Contribution Amount',
    loan_amount: 'Loan Amount',
    loan_purpose: 'Loan Purpose',
    submit_application: 'Submit Application',
    exceeds_limit: 'Amount exceeds your limit',
    payment_initiated_check_phone: 'Payment initiated. Check your phone.',
    sacco_savings: 'Savings',
    sacco_loans: 'Loans',
    sacco_groups: 'Groups',
    monthly_interest: 'Monthly Interest',
    max_loan: 'Max Loan',
    repayment_period: 'Repayment Period',
    months: 'months',
    annual_interest: 'Annual Interest',
    apply_now: 'Apply Now',
    no_active_loans: 'No active loans',
    amount_due: 'Amount Due',
    due_date: 'Due Date',
    members: 'Members',
    next_meeting: 'Next Meeting',
    your_contribution: 'Your Contribution',
    group_savings: 'Group Savings',
    contribute: 'Contribute',
    enter_amount: 'Enter amount',
    enter_purpose: 'Enter loan purpose',

    // Intelligence
    strong_market: 'Strong Market',
    weak_market: 'Weak Market',
    stable_market: 'Stable Market',
    ai_insights_label: 'AI Insights',
    high_demand: 'High Demand',
    todays_prices: "Today's Prices",
    now: 'Now',
    week_ago: '1 Week Ago',
    month_ago: '1 Month Ago',
    seven_day_forecast: '7-Day Forecast',
    best_time_sell: 'Best Time to Sell',
    last_updated: 'Last Updated',
    loading_intelligence: 'Loading market intelligence...',
    market_overview: 'Market Overview',
    price_trends: 'Price Trends',
    supply_demand: 'Supply & Demand',
    regional_prices: 'Regional Prices',
    crop_analysis: 'Crop Analysis',
    select_crop_analysis: 'Select a crop for detailed analysis',
    market_score: 'Market Score',
    trending_up: 'Trending Up',
    trending_down: 'Trending Down',

    // Deliveries extra
    no_available_jobs: 'No available jobs',
    no_active_jobs: 'No active deliveries',
    cargo_information: 'Cargo Information',
    crop_type_label: 'Crop Type',
    update_status: 'Update Status',
    delivery_note: 'Delivery Note',
    optimized_route: 'Optimized Route',
    enter_delivery_note: 'Enter delivery note...',
    delivery_weight: 'Weight',
    delivery_temperature: 'Temperature',
    sender: 'Sender',
    receiver: 'Receiver',

    // Orders extra
    escrow_protected: 'Escrow Protected',
    order_timeline: 'Order Timeline',
    payment_confirmed: 'Payment Confirmed',
    dispute_contact: 'Contact Support for Disputes',
    loading_orders: 'Loading orders...',
    order_placed: 'Order Placed',
    awaiting_payment: 'Awaiting Payment',
    rate_transaction: 'Rate Transaction',

    // Market extra
    ai_fair_price: 'AI Fair Price',
    offer_quantity: 'Offer Quantity (kg)',
    offer_price: 'Offer Price (KSh/kg)',
    offer_message: 'Message to Seller',
    submit_offer: 'Submit Offer',
    offer_submitted: 'Offer submitted successfully!',
    listed_price: 'Listed Price',
    ai_suggested: 'AI Suggested',
    fresh_harvest: 'Fresh Harvest',
    organic: 'Organic',
    seller_info: 'Seller Information',
    similar_listings: 'Similar Listings',

    // Sell extra
    step_x_of_y: 'Step %1 of %2',
    publishing: 'Publishing...',
    re_analyze: 'Re-analyze',
    more_photos_needed: 'More photos needed for accurate grading',
    grading_required: 'AI grading required before publishing',
    next: 'Next',
    previous: 'Previous',
    step_details: 'Details',
    step_photos: 'Photos',
    step_grading: 'Grading',
    step_harvest: 'Harvest',
    step_delivery: 'Delivery',
    step_review: 'Review',

    // Grade screen
    instant_grading_subtitle: 'Get instant quality grading and price suggestion',
    open_camera: 'Open Camera',
    choose_gallery: 'Choose from Gallery',
    what_grading: 'What are you grading?',
    analyze_quality: 'Analyze Quality',
    list_for_sale: 'List for Sale',
    grade_another: 'Grade Another',
    retake_photo: 'Retake Photo',
    list_your_produce: 'List Your Produce',
    quality_grade: 'Quality Grade',
    your_price_optional: 'Your Price (optional)',
    creating: 'Creating...',
    select_crop_type: 'Select Crop Type',
    listing_created: 'Listing Created!',
    permission_needed: 'Permission Needed',
    missing_info: 'Missing Info',
    camera_roll_required: 'Camera roll access is required',
    camera_required: 'Camera access is required',
    price_range: 'Price Range',
    market_trend: 'Market Trend',
    notes: 'Notes',
    view_market: 'View Market',
    missing_info_message: 'Please fill in quantity and location',

    // Privacy
    privacy_intro: 'SunHarvest Connect is committed to protecting your privacy.',
    data_collection_title: 'Data We Collect',
    data_collection_body: 'We collect your name, phone number, location, and transaction data to provide our services.',
    data_usage_title: 'How We Use Data',
    data_usage_body: 'Your data is used to facilitate marketplace transactions, AI grading, and personalized recommendations.',
    data_sharing_title: 'Data Sharing',
    data_sharing_body: 'We share limited data with transaction partners. We never sell your personal information.',
    data_security_title: 'Data Security',
    data_security_body: 'We use industry-standard encryption and security measures to protect your data.',
    your_rights_title: 'Your Rights',
    your_rights_body: 'You can request data access, correction, or deletion at any time through the app or by contacting support.',
    contact_privacy: 'For privacy inquiries, contact privacy@sunharvest.co.ke',
    last_updated_date: 'Last Updated: January 2025',

    // Toast / General UI
    coming_soon: 'Coming Soon',
    feature_coming_soon: 'This feature is coming soon!',
    network_error: 'Network error. Please try again.',
    copied: 'Copied to clipboard',
    saved_successfully: 'Saved successfully',
    deleted_successfully: 'Deleted successfully',
    no_results: 'No results found',
    pull_to_refresh: 'Pull to refresh',
    load_more: 'Load More',
    see_all: 'See All',
    done: 'Done',
    next_step: 'Next Step',
    share: 'Share',
    report: 'Report',
    dark_mode: 'Dark Mode',
    notifications: 'Notifications',
    version: 'Version',

    // Notifications
    notification_new_offer: 'New offer on your produce',
    notification_offer_accepted: 'Your offer was accepted',
    notification_payment_received: 'Payment received',
    notification_delivery_started: 'Delivery has started',
    notification_delivery_complete: 'Delivery completed',
    notification_transaction_complete: 'Transaction complete',
    mark_all_read: 'Mark all read',
    no_notifications: 'No notifications',
    no_notifications_yet: 'No notifications yet',
    just_now: 'Just now',
    minutes_ago: '%1 min ago',
    hours_ago: '%1 hours ago',

    // Public Profile
    view_profile: 'View Profile',
    active_listings: 'Active Listings',
    completed_deals: 'Completed Deals',

    // Rating
    rate_transaction: 'Rate this transaction',
    thanks_for_rating: 'Thanks for rating!',
    tap_to_rate: 'Tap a star to rate',

    // Location
    use_current_location: 'Use my current location',
    getting_location: 'Getting location...',
    location_permission_needed: 'Location permission is needed to use this feature',

    // Market
    no_listings_available: 'No listings available',
    try_again: 'Try Again',
  },

  sw: {
    // Common
    app_name: 'SunHarvest Connect',
    loading: 'Inapakia...',
    cancel: 'Ghairi',
    confirm: 'Thibitisha',
    save: 'Hifadhi',
    delete: 'Futa',
    edit: 'Hariri',
    search: 'Tafuta',
    filter: 'Chuja',
    all: 'Zote',
    view_all: 'Ona Zote',
    back: 'Rudi',
    continue: 'Endelea',
    submit: 'Wasilisha',
    close: 'Funga',
    yes: 'Ndiyo',
    no: 'Hapana',
    ok: 'Sawa',
    error: 'Hitilafu',
    success: 'Imefanikiwa',
    retry: 'Jaribu tena',

    // Auth
    welcome: 'Karibu',
    login: 'Ingia',
    register: 'Jisajili',
    phone_number: 'Nambari ya Simu',
    enter_phone: 'Ingiza nambari yako ya simu',
    pin: 'PIN',
    enter_pin: 'Ingiza PIN yako ya nambari 4',
    create_pin: 'Tengeneza PIN ya nambari 4',
    confirm_pin: 'Thibitisha PIN',
    name: 'Jina Kamili',
    enter_name: 'Ingiza jina lako kamili',
    location: 'Mahali',
    select_county: 'Chagua kaunti yako',
    user_type: 'Mimi ni...',
    farmer: 'Mkulima',
    buyer: 'Mnunuzi',
    transporter: 'Msafirishaji',
    login_success: 'Umeingia kikamilifu',
    register_success: 'Usajili umefanikiwa',
    invalid_credentials: 'Simu au PIN si sahihi',
    app_subtitle: 'Soko la AI kwa wakulima wa Kenya. Pata bei nzuri kwa mazao yako.',
    ai_quality_grading: 'Upimaji wa ubora wa AI',
    real_time_market_prices: 'Bei za soko za wakati halisi',
    direct_buyer_connections: 'Mawasiliano ya moja kwa moja na wanunuzi',
    get_started: 'Anza Sasa',
    have_account: 'Una akaunti tayari?',
    quick_demo: 'Demo ya Haraka',
    try_demo: 'Jaribu programu mara moja kama:',
    sign_in_subtitle: 'Ingia ili kufikia akaunti yako',
    register_subtitle: 'Jiunge na maelfu ya wakulima wanaopata bei nzuri',
    missing_fields: 'Sehemu Zinakosekana',
    missing_fields_login: 'Tafadhali ingiza simu na PIN',
    missing_fields_register: 'Tafadhali jaza sehemu zote',
    invalid_pin: 'PIN si Sahihi',
    invalid_pin_message: 'PIN lazima iwe nambari 4',
    pin_mismatch: 'PIN Hazifanani',
    pin_mismatch_message: 'PIN hazifanani',
    login_failed: 'Kuingia Kumeshindikana',
    login_failed_default: 'Kuingia kumeshindikana. Tafadhali angalia taarifa zako.',
    registration_failed: 'Usajili Umeshindikana',
    registration_failed_default: 'Usajili umeshindikana. Tafadhali jaribu tena.',
    demo_login_failed: 'Kuingia kwa Demo Kumeshindikana',
    demo_login_failed_message: 'Hakikisha seva inafanya kazi na database imejazwa.\n\nEndesha: npx ts-node scripts/seedListings.ts',
    no_account: 'Huna akaunti?',
    consent_agree: 'Nakubaliana na',
    consent_privacy_policy: 'Sera ya Faragha',
    consent_and: 'na',
    consent_terms: 'Masharti ya Huduma',
    consent_dpa: 'kama inavyohitajika na Sheria ya Ulinzi wa Data ya Kenya 2019.',
    consent_required: 'Idhini Inahitajika',
    consent_required_message: 'Lazima ukubaliane na Sera ya Faragha na Masharti ya Huduma kuunda akaunti.',
    demo_login_as: 'Demo kama %1',

    // Navigation
    home: 'Nyumbani',
    dashboard: 'Dashibodi',
    sell: 'Uza',
    market: 'Soko',
    orders: 'Oda',
    jobs: 'Kazi',
    deliveries: 'Usafirishaji',
    profile: 'Wasifu',
    sacco: 'SACCO',

    // Dashboard
    good_morning: 'Habari za asubuhi',
    good_afternoon: 'Habari za mchana',
    good_evening: 'Habari za jioni',
    ai_insights: 'Maarifa ya AI',
    quick_actions: 'Vitendo vya Haraka',
    market_prices: 'Bei za Soko',
    view_trends: 'Angalia mwenendo',
    todays_weather: 'Hali ya Hewa Leo',
    create_listing: 'Tengeneza Orodha',
    browse_market: 'Vinjari Soko',
    grade_and_list: 'Pima ubora na uorodheshe mazao',
    find_fresh_produce: 'Pata mazao mapya karibu nawe',
    find_deliveries: 'Pata kazi za usafirishaji karibu nawe',
    ai_prices: 'Bei za AI',
    my_orders: 'Oda Zangu',
    total_revenue: 'Mapato Jumla',
    total_spent: 'Matumizi Jumla',
    total_earnings: 'Mapato Jumla',
    listings: 'Orodha',
    offers: 'Ofa',
    rating: 'Kiwango',
    views: 'mitazamo',
    sales: 'mauzo',
    this_month: 'mwezi huu',
    sold: 'imeuzwa',
    total: 'jumla',
    reviews: 'maoni',
    purchases: 'manunuzi',
    active_now: 'hai sasa',
    ai_grade: 'Daraja la AI',

    // Market
    marketplace: 'Soko',
    market_intelligence: 'Akili ya Soko',
    available_listings: 'Orodha Zinazopatikana',
    todays_market_prices: 'Bei za Soko Leo',
    live: 'Moja kwa Moja',
    search_crops: 'Tafuta mazao, wakulima, maeneo...',
    no_listings: 'Hakuna Orodha',
    check_back: 'Rudi baadaye kwa orodha mpya',
    per_kg: 'kwa kilo',
    kg_available: 'kg inapatikana',
    make_offer: 'Toa Bei',
    ai_graded: 'Imepimwa na AI',
    contact_farmer: 'Wasiliana na Mkulima',
    contact_buyer: 'Wasiliana na Mnunuzi',
    call: 'Piga Simu',
    whatsapp: 'WhatsApp',
    escrow_protection: 'Ulinzi wa Escrow',
    escrow_description: 'Malipo yako yamehifadhiwa salama hadi uthibitishe kupokelewa',

    // Sell/Create Listing
    sell_produce: 'Uza Mazao',
    what_selling: 'Unauza nini?',
    select_crop: 'Chagua aina ya zao na ingiza maelezo',
    crop_type: 'Aina ya Zao',
    quantity: 'Kiasi',
    quantity_kg: 'Kiasi (kg)',
    price: 'Bei',
    price_per_kg: 'Bei kwa kilo (KSh)',
    description: 'Maelezo',
    description_optional: 'Maelezo (si lazima)',
    add_photos: 'Ongeza Picha',
    upload_photos: 'Pakia angalau picha 2 kwa upimaji wa AI',
    camera: 'Kamera',
    gallery: 'Galari',
    run_ai_grading: 'Fanya Upimaji wa AI',
    ai_quality_grade: 'Daraja la Ubora la AI',
    confident: 'uhakika',
    suggested_price: 'Bei Inayopendekezwa',
    harvest_details: 'Maelezo ya Mavuno',
    harvest_date: 'Tarehe ya Kuvuna',
    available_for: 'Inapatikana kwa (siku)',
    storage_conditions: 'Hali ya Kuhifadhi',
    cool_dry: 'Baridi & Kavu',
    refrigerated: 'Jokofu',
    room_temp: 'Joto la Chumba',
    delivery_options: 'Chaguo za Uwasilishaji',
    pickup_and_review: 'Mahali pa Kukusanya & Kagua',
    set_pickup_location: 'Weka mahali ambapo wanunuzi au wasafirishaji wanaweza kukusanya mazao yako',
    delivery_by_transporters: 'Usafirishaji unashughulikiwa na wasafirishaji',
    transporter_info: 'Wasafirishaji waliothibitishwa kwenye SunHarvest watasafirisha kwa wanunuzi. Wewe andaa tu kwa kukusanywa.',
    use_price: 'Tumia bei hii',
    your_price: 'Bei yako ya sasa',
    pickup_location: 'Mahali pa Kuchukua',
    delivery_available: 'Uwasilishaji Unapatikana?',
    delivery_radius: 'Umbali wa Uwasilishaji (km)',
    listing_summary: 'Muhtasari wa Orodha',
    total_value: 'Thamani Jumla',
    publish_listing: 'Chapisha Orodha',
    listing_published: 'Orodha Imechapishwa!',
    listing_failed: 'Imeshindwa kuchapisha orodha. Tafadhali jaribu tena.',
    listing_live: 'Orodha yako iko sokoni sasa.',

    // Orders
    active: 'Hai',
    history: 'Historia',
    pending: 'Inasubiri',
    accepted: 'Imekubaliwa',
    paid: 'Imelipwa',
    in_transit: 'Njiani',
    delivered: 'Imewasilishwa',
    completed: 'Imekamilika',
    cancelled: 'Imeghairiwa',
    disputed: 'Ina Mgogoro',
    no_orders: 'Hakuna oda',
    accept_offer: 'Kubali Ofa',
    decline_offer: 'Kataa Ofa',
    offer_accepted: 'Ofa imekubaliwa',
    offer_declined: 'Ofa imekataliwa',
    pay_mpesa: 'Lipa na M-Pesa',
    payment_initiated: 'Malipo Yameanzishwa',
    check_phone: 'Angalia simu yako kwa M-Pesa.',
    confirm_delivery: 'Thibitisha Uwasilishaji',
    confirm_receipt: 'Thibitisha Kupokea',
    delivery_confirmed: 'Uwasilishaji Umethibitishwa',
    payment_released: 'Malipo yametolewa kwa mkulima.',
    mark_delivered: 'Weka kama Imewasilishwa',
    escrow_held: 'Fedha zimehifadhiwa',
    total_amount: 'Jumla ya Kiasi',
    order_details: 'Maelezo ya Oda',

    // Trust Score
    trust_score: 'Alama ya Uaminifu',
    your_trust_score: 'Alama Yako ya Uaminifu',
    transactions: 'Miamala',
    member_since: 'Mwanachama Tangu',
    achievements: 'Mafanikio',
    score_breakdown: 'Mgawanyo wa Alama',
    completion_rate: 'Kiwango cha Kukamilisha',
    partner_rating: 'Kiwango cha Mshirika',
    account_age: 'Umri wa Akaunti',
    verification: 'Uthibitisho',
    response_time: 'Muda wa Kujibu',
    dispute_history: 'Historia ya Migogoro',
    ai_insights_title: 'Maarifa ya AI',

    // Profile
    account_info: 'Taarifa za Akaunti',
    account_information: 'Taarifa za Akaunti',
    transaction_history: 'Historia ya Miamala',
    select_language: 'Chagua Lugha',
    tagline: 'Kuwawezesha Wakulima wa Kenya',
    recent_activity: 'Shughuli za Hivi Karibuni',
    settings: 'Mipangilio',
    push_notifications: 'Arifa za Push',
    sms_alerts: 'Arifa za SMS',
    edit_profile: 'Hariri Wasifu',
    change_pin: 'Badilisha PIN',
    language: 'Lugha',
    english: 'Kiingereza',
    swahili: 'Kiswahili',
    support: 'Msaada',
    help_center: 'Kituo cha Msaada',
    contact_support: 'Wasiliana na Msaada',
    terms_privacy: 'Masharti & Faragha',
    privacy_policy: 'Sera ya Faragha',
    delete_account: 'Futa Akaunti',
    about: 'Kuhusu SunHarvest',
    logout: 'Ondoka',
    logout_confirm: 'Una uhakika unataka kuondoka?',
    verify_account: 'Thibitisha Akaunti',
    verified: 'Imethibitishwa',

    // Deliveries (Transporter)
    available_jobs: 'Kazi Zinazopatikana',
    my_jobs: 'Kazi Zangu',
    todays_earnings: 'Mapato ya Leo',
    active_jobs: 'Kazi Hai',
    pickup: 'Kuchukua',
    delivery: 'Kuwasilisha',
    distance: 'Umbali',
    payment: 'Malipo',
    deadline: 'Mwisho',
    accept_job: 'Kubali Kazi',
    job_accepted: 'Kazi imekubaliwa!',
    contact_farmer_pickup: 'Wasiliana na mkulima kupanga kuchukua.',
    cargo_info: 'Taarifa za Mizigo',
    route: 'Njia',
    contacts: 'Mawasiliano',
    special_instructions: 'Maelekezo Maalum',
    mark_picked_up: 'Weka kama Imechukuliwa',
    start_delivery: 'Anza Kuwasilisha',
    complete_get_paid: 'Kamilisha & Lipwe',
    ai_route_suggestion: 'Pendekezo la Njia la AI',

    // AI Features
    ai_price_suggestion: 'Pendekezo la Bei la AI',
    recommended_price: 'Bei Inayopendekezwa',
    market_average: 'Wastani wa Soko',
    price_trend: 'Mwenendo wa Bei',
    rising: 'Inapanda',
    stable: 'Imara',
    falling: 'Inashuka',
    demand_level: 'Kiwango cha Mahitaji',
    high: 'Juu',
    normal: 'Kawaida',
    low: 'Chini',
    success_estimate: 'Makadirio ya Mafanikio',
    estimated_days: 'Siku za Kuuza (Makadirio)',
    probability: 'Uwezekano wa Kuuza',
    fast: 'Haraka',
    slow: 'Polepole',
    unlikely: 'Haiwezekani',

    // Grades
    premium: 'Hali ya Juu',
    grade_a: 'Daraja A',
    grade_b: 'Daraja B',
    grade_c: 'Daraja C',
    reject: 'Imekataliwa',
    grade: 'Daraja',
    grade_produce: 'Pima Mazao',
    take_photo: 'Piga picha ya mazao yako',
    instant_grading_subtitle: 'Pata upimaji wa ubora na pendekezo la bei papo hapo',
    open_camera: 'Fungua Kamera',
    choose_gallery: 'Chagua kutoka Galari',
    what_grading: 'Unapima nini?',
    select_from_gallery: 'Chagua kutoka Galari',
    analyzing: 'Inachunguza...',
    analyze_quality: 'Chambua Ubora',
    quality_analysis: 'Uchambuzi wa Ubora',
    quality_grade: 'Daraja la Ubora',
    confidence: 'Uhakika',
    grade_details: 'Maelezo ya Daraja',
    freshness: 'Uchangamfu',
    size_uniformity: 'Usawa wa Ukubwa',
    color_quality: 'Ubora wa Rangi',
    defects: 'Kasoro',
    recommendations: 'Mapendekezo',
    price_range: 'Masafa ya Bei',
    market_trend: 'Mwenendo wa Soko',
    notes: 'Maelezo',
    list_for_sale: 'Orodhesha kwa Kuuza',
    grade_another: 'Pima Nyingine',
    retake_photo: 'Piga Picha Tena',
    list_your_produce: 'Orodhesha Mazao Yako',
    your_price_optional: 'Bei Yako (si lazima)',
    creating: 'Inaunda...',
    select_crop_type: 'Chagua Aina ya Zao',
    listing_created: 'Orodha Imeundwa!',
    permission_needed: 'Idhini inahitajika',
    missing_info: 'Taarifa Zinakosekana',
    camera_roll_required: 'Upatikanaji wa galari ya picha unahitajika',
    camera_required: 'Upatikanaji wa kamera unahitajika',

    // SACCO
    total_savings: 'Akiba Jumla',
    interest_earned: 'Riba Iliyopatikana',
    loan_balance: 'Salio la Mkopo',
    credit_score: 'Alama ya Mkopo',
    make_contribution: 'Fanya Mchango',
    apply_loan: 'Omba Mkopo',
    loan_products: 'Bidhaa za Mikopo',
    recent_transactions: 'Miamala ya Hivi Karibuni',
    my_sacco_groups: 'Vikundi Vyangu vya SACCO',
    join_sacco: 'Jiunge na SACCO',
    active_loans: 'Mikopo Hai',
    make_repayment: 'Fanya Malipo',
    loan_terms: 'Masharti ya Mkopo',
    pay_mpesa_prompt: 'Angalia simu yako kwa M-Pesa',
    contribution_amount: 'Kiasi cha Mchango',
    loan_amount: 'Kiasi cha Mkopo',
    loan_purpose: 'Sababu ya Mkopo',
    submit_application: 'Wasilisha Maombi',
    exceeds_limit: 'Kiasi kinazidi kikomo chako',
    payment_initiated_check_phone: 'Malipo yameanzishwa. Angalia simu yako.',
    sacco_savings: 'Akiba',
    sacco_loans: 'Mikopo',
    sacco_groups: 'Vikundi',
    monthly_interest: 'Riba ya Mwezi',
    max_loan: 'Mkopo wa Juu',
    repayment_period: 'Kipindi cha Malipo',
    months: 'miezi',
    annual_interest: 'Riba ya Mwaka',
    apply_now: 'Omba Sasa',
    no_active_loans: 'Hakuna mikopo hai',
    amount_due: 'Kiasi Kinachostahili',
    due_date: 'Tarehe ya Mwisho',
    members: 'Wanachama',
    next_meeting: 'Mkutano Ujao',
    your_contribution: 'Mchango Wako',
    group_savings: 'Akiba ya Kikundi',
    contribute: 'Changia',
    enter_amount: 'Ingiza kiasi',
    enter_purpose: 'Ingiza sababu ya mkopo',

    // Intelligence
    strong_market: 'Soko Imara',
    weak_market: 'Soko Dhaifu',
    stable_market: 'Soko Thabiti',
    ai_insights_label: 'Maarifa ya AI',
    high_demand: 'Mahitaji Makubwa',
    todays_prices: 'Bei za Leo',
    now: 'Sasa',
    week_ago: 'Wiki 1 Iliyopita',
    month_ago: 'Mwezi 1 Uliopita',
    seven_day_forecast: 'Utabiri wa Siku 7',
    best_time_sell: 'Wakati Bora wa Kuuza',
    last_updated: 'Ilisasishwa Mwisho',
    loading_intelligence: 'Inapakia akili ya soko...',
    market_overview: 'Muhtasari wa Soko',
    price_trends: 'Mwenendo wa Bei',
    supply_demand: 'Ugavi na Mahitaji',
    regional_prices: 'Bei za Mikoa',
    crop_analysis: 'Uchambuzi wa Mazao',
    select_crop_analysis: 'Chagua zao kwa uchambuzi wa kina',
    market_score: 'Alama ya Soko',
    trending_up: 'Inapanda',
    trending_down: 'Inashuka',

    // Deliveries extra
    no_available_jobs: 'Hakuna kazi zinazopatikana',
    no_active_jobs: 'Hakuna usafirishaji hai',
    cargo_information: 'Taarifa za Mizigo',
    crop_type_label: 'Aina ya Zao',
    update_status: 'Sasisha Hali',
    delivery_note: 'Maelezo ya Usafirishaji',
    optimized_route: 'Njia Bora',
    enter_delivery_note: 'Ingiza maelezo ya usafirishaji...',
    delivery_weight: 'Uzito',
    delivery_temperature: 'Joto',
    sender: 'Mtumaji',
    receiver: 'Mpokeaji',

    // Orders extra
    escrow_protected: 'Inalindwa na Escrow',
    order_timeline: 'Mpangilio wa Oda',
    payment_confirmed: 'Malipo Yamethibitishwa',
    dispute_contact: 'Wasiliana na Msaada kwa Migogoro',
    loading_orders: 'Inapakia oda...',
    order_placed: 'Oda Imewekwa',
    awaiting_payment: 'Inasubiri Malipo',
    rate_transaction: 'Kadiria Muamala',

    // Market extra
    ai_fair_price: 'Bei ya Haki ya AI',
    offer_quantity: 'Kiasi cha Ofa (kg)',
    offer_price: 'Bei ya Ofa (KSh/kg)',
    offer_message: 'Ujumbe kwa Muuzaji',
    submit_offer: 'Wasilisha Ofa',
    offer_submitted: 'Ofa imewasilishwa!',
    listed_price: 'Bei Iliyoorodheshwa',
    ai_suggested: 'Iliyopendekezwa na AI',
    fresh_harvest: 'Mavuno Mapya',
    organic: 'Asili',
    seller_info: 'Taarifa za Muuzaji',
    similar_listings: 'Orodha Zinazofanana',

    // Sell extra
    step_x_of_y: 'Hatua %1 ya %2',
    publishing: 'Inachapisha...',
    re_analyze: 'Chambua Tena',
    more_photos_needed: 'Picha zaidi zinahitajika kwa upimaji sahihi',
    grading_required: 'Upimaji wa AI unahitajika kabla ya kuchapisha',
    next: 'Endelea',
    previous: 'Iliyopita',
    step_details: 'Maelezo',
    step_photos: 'Picha',
    step_grading: 'Upimaji',
    step_harvest: 'Mavuno',
    step_delivery: 'Usafirishaji',
    step_review: 'Kagua',

    // Grade screen
    instant_grading_subtitle: 'Pata upimaji wa ubora na bei papo hapo',
    open_camera: 'Fungua Kamera',
    choose_gallery: 'Chagua kutoka Galari',
    what_grading: 'Unapima nini?',
    analyze_quality: 'Chambua Ubora',
    list_for_sale: 'Orodhesha Kuuza',
    grade_another: 'Pima Kingine',
    retake_photo: 'Piga Picha Tena',
    list_your_produce: 'Orodhesha Mazao Yako',
    quality_grade: 'Daraja la Ubora',
    your_price_optional: 'Bei Yako (si lazima)',
    creating: 'Inatengeneza...',
    select_crop_type: 'Chagua Aina ya Zao',
    listing_created: 'Orodha Imetengenezwa!',
    permission_needed: 'Ruhusa Inahitajika',
    missing_info: 'Taarifa Zinakosekana',
    camera_roll_required: 'Ruhusa ya galari inahitajika',
    camera_required: 'Ruhusa ya kamera inahitajika',
    price_range: 'Kiwango cha Bei',
    market_trend: 'Mwenendo wa Soko',
    notes: 'Maelezo',
    view_market: 'Tazama Soko',
    missing_info_message: 'Tafadhali jaza kiasi na mahali',

    // Privacy
    privacy_intro: 'SunHarvest Connect imejitolea kulinda faragha yako.',
    data_collection_title: 'Data Tunazokusanya',
    data_collection_body: 'Tunakusanya jina lako, nambari ya simu, mahali, na data ya miamala ili kutoa huduma zetu.',
    data_usage_title: 'Jinsi Tunavyotumia Data',
    data_usage_body: 'Data yako inatumika kuwezesha miamala ya soko, upimaji wa AI, na mapendekezo binafsi.',
    data_sharing_title: 'Kushiriki Data',
    data_sharing_body: 'Tunashiriki data kidogo na washirika wa miamala. Hatuwahi kuuza taarifa zako binafsi.',
    data_security_title: 'Usalama wa Data',
    data_security_body: 'Tunatumia usimbaji fiche na hatua za usalama za kiwango cha juu kulinda data yako.',
    your_rights_title: 'Haki Zako',
    your_rights_body: 'Unaweza kuomba upatikanaji, marekebisho, au ufutaji wa data wakati wowote kupitia programu au kwa kuwasiliana na msaada.',
    contact_privacy: 'Kwa maswali ya faragha, wasiliana na privacy@sunharvest.co.ke',
    last_updated_date: 'Ilisasishwa Mwisho: Januari 2025',

    // Toast / General UI
    coming_soon: 'Inakuja Hivi Karibuni',
    feature_coming_soon: 'Kipengele hiki kinakuja hivi karibuni!',
    network_error: 'Hitilafu ya mtandao. Tafadhali jaribu tena.',
    copied: 'Imenakiliwa',
    saved_successfully: 'Imehifadhiwa',
    deleted_successfully: 'Imefutwa',
    no_results: 'Hakuna matokeo',
    pull_to_refresh: 'Vuta kusasisha',
    load_more: 'Pakia Zaidi',
    see_all: 'Ona Zote',
    done: 'Imekamilika',
    next_step: 'Hatua Inayofuata',
    share: 'Shiriki',
    report: 'Ripoti',
    dark_mode: 'Hali ya Giza',
    notifications: 'Arifa',
    version: 'Toleo',

    // Notifications
    notification_new_offer: 'Ofa mpya kwa mazao yako',
    notification_offer_accepted: 'Ofa yako imekubaliwa',
    notification_payment_received: 'Malipo yamepokelewa',
    notification_delivery_started: 'Usafirishaji umeanza',
    notification_delivery_complete: 'Usafirishaji umekamilika',
    notification_transaction_complete: 'Muamala umekamilika',
    mark_all_read: 'Weka zote zimesomwa',
    no_notifications: 'Hakuna taarifa',
    no_notifications_yet: 'Hakuna arifa bado',
    just_now: 'Sasa hivi',
    minutes_ago: 'Dakika %1 zilizopita',
    hours_ago: 'Saa %1 zilizopita',

    // Public Profile
    view_profile: 'Tazama Wasifu',
    active_listings: 'Orodha Hai',
    completed_deals: 'Miamala Iliyokamilika',

    // Rating
    rate_transaction: 'Kadiria muamala huu',
    thanks_for_rating: 'Asante kwa kukadiria!',
    tap_to_rate: 'Gusa nyota kukadiria',

    // Location
    use_current_location: 'Tumia eneo langu la sasa',
    getting_location: 'Inapata eneo...',
    location_permission_needed: 'Ruhusa ya eneo inahitajika kutumia kipengele hiki',

    // Market
    no_listings_available: 'Hakuna orodha zinazopatikana',
    try_again: 'Jaribu Tena',
  },
};

type TranslationKeys = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: TranslationKeys) => string;
  isSwahili: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const saved = await AsyncStorage.getItem('language');
      if (saved === 'en' || saved === 'sw') {
        setLanguageState(saved);
      }
    } catch (error) {
      console.error('Error loading language:', error);
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem('language', lang);
      setLanguageState(lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key: TranslationKeys): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        isSwahili: language === 'sw',
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export type { Language, TranslationKeys };
